export const LANGUAGES = [
  {code: "any", name: "Any language"},
  {code: "ar", name: "Arabic"},
  {code: "ar-x-fm", name: "Arabic (Feminine)"},
  {code: "bn", name: "Bangla"},
  {code: "eu", name: "Basque"},
  {code: "bg", name: "Bulgarian"},
  {code: "ca", name: "Catalan"},
  {code: "hr", name: "Croatian"},
  {code: "cs", name: "Czech"},
  {code: "da", name: "Danish"},
  {code: "nl", name: "Dutch"},
  {code: "en", name: "English"},
  {code: "fi", name: "Finnish"},
  {code: "fr", name: "French"},
  {code: "de", name: "German"},
  {code: "el", name: "Greek"},
  {code: "gu", name: "Gujarati"},
  {code: "he", name: "Hebrew"},
  {code: "hi", name: "Hindi"},
  {code: "hu", name: "Hungarian"},
  {code: "id", name: "Indonesian"},
  {code: "it", name: "Italian"},
  {code: "ja", name: "Japanese"},
  {code: "kn", name: "Kannada"},
  {code: "ko", name: "Korean"},
  {code: "mr", name: "Marathi"},
  {code: "no", name: "Norwegian"},
  {code: "fa", name: "Persian"},
  {code: "pl", name: "Polish"},
  {code: "pt", name: "Portuguese"},
  {code: "ro", name: "Romanian"},
  {code: "ru", name: "Russian"},
  {code: "sr", name: "Serbian"},
  {code: "zh-cn", name: "Simplified Chinese"},
  {code: "sk", name: "Slovak"},
  {code: "es", name: "Spanish"},
  {code: "sv", name: "Swedish"},
  {code: "ta", name: "Tamil"},
  {code: "th", name: "Thai"},
  {code: "zh-tw", name: "Traditional Chinese"},
  {code: "tr", name: "Turkish"},
  {code: "uk", name: "Ukrainian"},
  {code: "ur", name: "Urdu"},
  {code: "vi", name: "Vietnamese"},
];